BrowserCategory["sneg documentation", None, 
 {BrowserCategory["Introduction", None, 
   {Item["Quick start", "quickstart.nb", CopyTag -> None, 
     IndexTag -> "snegquickstart"]}], BrowserCategory["Reference guide", 
   None, {{Item["acmt", "acmt.nb", CopyTag -> None, IndexTag -> "acmt"]}, 
    {Item["antikomutator", "antikomutator.nb", CopyTag -> None, 
      IndexTag -> "antikomutator"]}, {Item["ap", "ap.nb", CopyTag -> None, 
      IndexTag -> "ap"]}, {Item["applybasis", "applybasis.nb", 
      CopyTag -> None, IndexTag -> "applybasis"]}, 
    {Item["basis", "basis.nb", CopyTag -> None, IndexTag -> "basis"]}, 
    {Item["bosonQ", "bosonQ.nb", CopyTag -> None, IndexTag -> "bosonQ"]}, 
    {Item["braketrule", "braketrule.nb", CopyTag -> None, 
      IndexTag -> "braketrule"]}, {Item["braketvc", "braketvc.nb", 
      CopyTag -> None, IndexTag -> "braketvc"], Item["braketop", 
      "braketvc.nb", CopyTag -> None, IndexTag -> "braketop"], 
     Item["expvvc", "braketvc.nb", CopyTag -> None, IndexTag -> "expvvc"], 
     Item["expvop", "braketvc.nb", CopyTag -> None, IndexTag -> "expvop"]}, 
    {Item["bra", "bra.nb", CopyTag -> None, IndexTag -> "bra"], 
     Item["ket", "bra.nb", CopyTag -> None, IndexTag -> "ket"]}, 
    {Item["bzvc2bzop", "bzvc2bzop.nb", CopyTag -> None, 
      IndexTag -> "bzvc2bzop"], Item["bzop2bzvc", "bzvc2bzop.nb", 
      CopyTag -> None, IndexTag -> "bzop2bzvc"]}, 
    {Item["chargecharge", "chargecharge.nb", CopyTag -> None, 
      IndexTag -> "chargecharge"]}, {Item["cmt", "cmt.nb", CopyTag -> None, 
      IndexTag -> "cmt"]}, {Item["conj", "conj.nb", CopyTag -> None, 
      IndexTag -> "conj"]}, {Item["contraction", "contraction.nb", 
      CopyTag -> None, IndexTag -> "contraction"]}, 
    {Item["dd", "dd.nb", CopyTag -> None, IndexTag -> "dd"]}, 
    {Item["decomposevc", "decomposevc.nb", CopyTag -> None, 
      IndexTag -> "decomposevc"], Item["decomposeop", "decomposevc.nb", 
      CopyTag -> None, IndexTag -> "decomposeop"]}, 
    {Item["direct", "direct.nb", CopyTag -> None, IndexTag -> "direct"]}, 
    {Item["dropemptysubspaces", "dropemptysubspaces.nb", CopyTag -> None, 
      IndexTag -> "dropemptysubspaces"]}, 
    {Item["fermionQ", "fermionQ.nb", CopyTag -> None, 
      IndexTag -> "fermionQ"]}, {Item["goodopQ", "goodopQ.nb", 
      CopyTag -> None, IndexTag -> "goodopQ"]}, 
    {Item["grassmanQ", "grassmanQ.nb", CopyTag -> None, 
      IndexTag -> "grassmanQ"]}, {Item["halfintegerQ", "halfintegerQ.nb", 
      CopyTag -> None, IndexTag -> "halfintegerQ"]}, 
    {Item["hamiltonian", "hamiltonian.nb", CopyTag -> None, 
      IndexTag -> "hamiltonian"]}, {Item["holehop", "holehop.nb", 
      CopyTag -> None, IndexTag -> "holehop"]}, 
    {Item["hop", "hop.nb", CopyTag -> None, IndexTag -> "hop"]}, 
    {Item["hubbard", "hubbard.nb", CopyTag -> None, IndexTag -> "hubbard"], 
     Item["isozsq", "hubbard.nb", CopyTag -> None, IndexTag -> "isozsq"]}, 
    {Item["inner", "inner.nb", CopyTag -> None, IndexTag -> "inner"]}, 
    {Item["invertspin", "invertspin.nb", CopyTag -> None, 
      IndexTag -> "invertspin"]}, {Item["isannihilation", 
      "isannihilation.nb", CopyTag -> None, IndexTag -> "isannihilation"], 
     Item["iscreation", "isannihilation.nb", CopyTag -> None, 
      IndexTag -> "iscreation"]}, {Item["isnumericQ", "isnumericQ.nb", 
      CopyTag -> None, IndexTag -> "isnumericQ"]}, 
    {Item["isospinxyz", "isospinxyz.nb", CopyTag -> None, 
      IndexTag -> "isospinxyz"], Item["isospinx", "isospinxyz.nb", 
      CopyTag -> None, IndexTag -> "isospinx"], Item["isospiny", 
      "isospinxyz.nb", CopyTag -> None, IndexTag -> "isospiny"], 
     Item["isospinz", "isospinxyz.nb", CopyTag -> None, 
      IndexTag -> "isospinz"], Item["isospinplus", "isospinxyz.nb", 
      CopyTag -> None, IndexTag -> "isospinplus"], Item["isospinminus", 
      "isospinxyz.nb", CopyTag -> None, IndexTag -> "isospinminus"]}, 
    {Item["komutator", "komutator.nb", CopyTag -> None, 
      IndexTag -> "komutator"]}, {Item["majoranaQ", "majoranaQ.nb", 
      CopyTag -> None, IndexTag -> "majoranaQ"]}, 
    {Item["makeallmatricesbzvc", "makeallmatricesbzvc.nb", CopyTag -> None, 
      IndexTag -> "makeallmatricesbzvc"], Item["makeallmatricesbzop", 
      "makeallmatricesbzvc.nb", CopyTag -> None, 
      IndexTag -> "makeallmatricesbzop"]}, 
    {Item["makebasis", "makebasis.nb", CopyTag -> None, 
      IndexTag -> "makebasis"]}, {Item["makematricesbzop", 
      "makematricesbzop.nb", CopyTag -> None, 
      IndexTag -> "makematricesbzop"], Item["makematricesbzvc", 
      "makematricesbzop.nb", CopyTag -> None, 
      IndexTag -> "makematricesbzvc"]}, 
    {Item["manyisospin", "manyisospin.nb", CopyTag -> None, 
      IndexTag -> "manyisospin"]}, {Item["manyspin", "manyspin.nb", 
      CopyTag -> None, IndexTag -> "manyspin"]}, 
    {Item["maskOp", "maskOp.nb", CopyTag -> None, IndexTag -> "maskOp"]}, 
    {Item["matrixrepresentationvc", "matrixrepresentationvc.nb", 
      CopyTag -> None, IndexTag -> "matrixrepresentationvc"], 
     Item["matrixrepresentationvcsparse", "matrixrepresentationvc.nb", 
      CopyTag -> None, IndexTag -> "matrixrepresentationvcsparse"], 
     Item["matrixrepresentationvcfast", "matrixrepresentationvc.nb", 
      CopyTag -> None, IndexTag -> "matrixrepresentationvcfast"], 
     Item["matrixrepresentationop", "matrixrepresentationvc.nb", 
      CopyTag -> None, IndexTag -> "matrixrepresentationop"], 
     Item["makematricesbzvc", "matrixrepresentationvc.nb", CopyTag -> None, 
      IndexTag -> "makematricesbzvc"], Item["makematricesbzop", 
      "matrixrepresentationvc.nb", CopyTag -> None, 
      IndexTag -> "makematricesbzop"]}, 
    {Item["mcross", "mcross.nb", CopyTag -> None, IndexTag -> "mcross"]}, 
    {Item["mergebasis", "mergebasis.nb", CopyTag -> None, 
      IndexTag -> "mergebasis"]}, {Item["nambu", "nambu.nb", CopyTag -> None, 
      IndexTag -> "nambu"]}, {Item["nc", "nc.nb", CopyTag -> None, 
      IndexTag -> "nc"]}, {Item["ndx2op", "ndx2op.nb", CopyTag -> None, 
      IndexTag -> "ndx2op"]}, {Item["normalorder", "normalorder.nb", 
      CopyTag -> None, IndexTag -> "normalorder"], Item["normalorderwick", 
      "normalorder.nb", CopyTag -> None, IndexTag -> "normalorderwick"]}, 
    {Item["normvc", "normvc.nb", CopyTag -> None, IndexTag -> "normvc"], 
     Item["normop", "normvc.nb", CopyTag -> None, IndexTag -> "normop"]}, 
    {Item["number", "number.nb", CopyTag -> None, IndexTag -> "number"]}, 
    {Item["op2ndx", "op2ndx.nb", CopyTag -> None, IndexTag -> "op2ndx"]}, 
    {Item["operatorQ", "operatorQ.nb", CopyTag -> None, 
      IndexTag -> "operatorQ"]}, {Item["ordering", "ordering.nb", 
      CopyTag -> None, IndexTag -> "ordering"]}, 
    {Item["orthogvc", "orthogvc.nb", CopyTag -> None, 
      IndexTag -> "orthogvc"], Item["orthogop", "orthogvc.nb", 
      CopyTag -> None, IndexTag -> "orthogop"]}, 
    {Item["outer", "outer.nb", CopyTag -> None, IndexTag -> "outer"]}, 
    {Item["PauliX", "PauliX.nb", CopyTag -> None, IndexTag -> "PauliX"], 
     Item["PauliY", "PauliX.nb", CopyTag -> None, IndexTag -> "PauliY"], 
     Item["PauliZ", "PauliX.nb", CopyTag -> None, IndexTag -> "PauliZ"], 
     Item["PauliPlus", "PauliX.nb", CopyTag -> None, 
      IndexTag -> "PauliPlus"], Item["PauliMinus", "PauliX.nb", 
      CopyTag -> None, IndexTag -> "PauliMinus"]}, 
    {Item["phononnumber", "phononnumber.nb", CopyTag -> None, 
      IndexTag -> "phononnumber"]}, {Item["phononplus", "phononplus.nb", 
      CopyTag -> None, IndexTag -> "phononplus"], Item["phononminus", 
      "phononplus.nb", CopyTag -> None, IndexTag -> "phononminus"]}, 
    {Item["pow", "pow.nb", CopyTag -> None, IndexTag -> "pow"]}, 
    {Item["projector", "projector.nb", CopyTag -> None, 
      IndexTag -> "projector"], Item["projector0", "projector.nb", 
      CopyTag -> None, IndexTag -> "projector0"], Item["projector1", 
      "projector.nb", CopyTag -> None, IndexTag -> "projector1"], 
     Item["projector2", "projector.nb", CopyTag -> None, 
      IndexTag -> "projector2"], Item["projectorUP", "projector.nb", 
      CopyTag -> None, IndexTag -> "projectorUP"], 
     Item["projectorDO", "projector.nb", CopyTag -> None, 
      IndexTag -> "projectorDO"], Item["projector02", "projector.nb", 
      CopyTag -> None, IndexTag -> "projector02"]}, 
    {Item["qsbasis", "qsbasis.nb", CopyTag -> None, IndexTag -> "qsbasis"], 
     Item["qsbasisvc", "qsbasis.nb", CopyTag -> None, 
      IndexTag -> "qsbasisvc"]}, {Item["qszbasis", "qszbasis.nb", 
      CopyTag -> None, IndexTag -> "qszbasis"], Item["qszbasisvc", 
      "qszbasis.nb", CopyTag -> None, IndexTag -> "qszbasisvc"]}, 
    {Item["quickISObasis", "quickISObasis.nb", CopyTag -> None, 
      IndexTag -> "quickISObasis"]}, 
    {Item["scalarproductop", "scalarproductop.nb", CopyTag -> None, 
      IndexTag -> "scalarproductop"]}, 
    {Item["scalarproductvc", "scalarproductvc.nb", CopyTag -> None, 
      IndexTag -> "scalarproductvc"]}, {Item["SimplifyKD", "SimplifyKD.nb", 
      CopyTag -> None, IndexTag -> "SimplifyKD"]}, 
    {Item["snegAssuming", "snegAssuming.nb", CopyTag -> None, 
      IndexTag -> "snegAssuming"]}, {Item["snegbosonoperators", 
      "snegbosonoperators.nb", CopyTag -> None, 
      IndexTag -> "snegbosonoperators"]}, 
    {Item["snegcomplexconstants", "snegcomplexconstants.nb", CopyTag -> None, 
      IndexTag -> "snegcomplexconstants"]}, 
    {Item["snegfermionoperators", "snegfermionoperators.nb", CopyTag -> None, 
      IndexTag -> "snegfermionoperators"]}, 
    {Item["snegfreeindexes", "snegfreeindexes.nb", CopyTag -> None, 
      IndexTag -> "snegfreeindexes"]}, {Item["sneggrassmanconstants", 
      "sneggrassmanconstants.nb", CopyTag -> None, 
      IndexTag -> "sneggrassmanconstants"]}, 
    {Item["snegmajoranaoperators", "snegmajoranaoperators.nb", 
      CopyTag -> None, IndexTag -> "snegmajoranaoperators"]}, 
    {Item["snegold2newrules", "snegold2newrules.nb", CopyTag -> None, 
      IndexTag -> "snegold2newrules"]}, 
    {Item["snegOrderedQ", "snegOrderedQ.nb", CopyTag -> None, 
      IndexTag -> "snegOrderedQ"]}, {Item["snegrealconstants", 
      "snegrealconstants.nb", CopyTag -> None, 
      IndexTag -> "snegrealconstants"]}, 
    {Item["snegSeries", "snegSeries.nb", CopyTag -> None, 
      IndexTag -> "snegSeries"]}, {Item["SnegSimplify", "SnegSimplify.nb", 
      CopyTag -> None, IndexTag -> "SnegSimplify"]}, 
    {Item["spinbra", "spinbra.nb", CopyTag -> None, IndexTag -> "spinbra"], 
     Item["spinket", "spinbra.nb", CopyTag -> None, IndexTag -> "spinket"], 
     Item["spinbasis", "spinbra.nb", CopyTag -> None, 
      IndexTag -> "spinbasis"]}, {Item["spinfliphop", "spinfliphop.nb", 
      CopyTag -> None, IndexTag -> "spinfliphop"]}, 
    {Item["spinketbraX", "spinketbraX.nb", CopyTag -> None, 
      IndexTag -> "spinketbraX"], Item["spinketbraY", "spinketbraX.nb", 
      CopyTag -> None, IndexTag -> "spinketbraY"], 
     Item["spinketbraZ", "spinketbraX.nb", CopyTag -> None, 
      IndexTag -> "spinketbraZ"], Item["spinketbraP", "spinketbraX.nb", 
      CopyTag -> None, IndexTag -> "spinketbraP"], 
     Item["spinketbraM", "spinketbraX.nb", CopyTag -> None, 
      IndexTag -> "spinketbraM"]}, {Item["spinmatrixX", "spinmatrixX.nb", 
      CopyTag -> None, IndexTag -> "spinmatrixX"], 
     Item["spinmatrixY", "spinmatrixX.nb", CopyTag -> None, 
      IndexTag -> "spinmatrixY"], Item["spinmatrixZ", "spinmatrixX.nb", 
      CopyTag -> None, IndexTag -> "spinmatrixZ"], 
     Item["spinmatrixP", "spinmatrixX.nb", CopyTag -> None, 
      IndexTag -> "spinmatrixP"], Item["spinmatrixM", "spinmatrixX.nb", 
      CopyTag -> None, IndexTag -> "spinmatrixM"]}, 
    {Item["spinspin", "spinspin.nb", CopyTag -> None, 
      IndexTag -> "spinspin"], Item["spinspinpm", "spinspin.nb", 
      CopyTag -> None, IndexTag -> "spinspinpm"], Item["spinspinmp", 
      "spinspin.nb", CopyTag -> None, IndexTag -> "spinspinmp"], 
     Item["spinspinxy", "spinspin.nb", CopyTag -> None, 
      IndexTag -> "spinspinxy"], Item["spinspinz", "spinspin.nb", 
      CopyTag -> None, IndexTag -> "spinspinz"]}, 
    {Item["spinspinsymmetric", "spinspinsymmetric.nb", CopyTag -> None, 
      IndexTag -> "spinspinsymmetric"]}, 
    {Item["spinx", "spinxyz.nb", CopyTag -> None, IndexTag -> "spinx"], 
     Item["spiny", "spinxyz.nb", CopyTag -> None, IndexTag -> "spiny"], 
     Item["spinz", "spinxyz.nb", CopyTag -> None, IndexTag -> "spinz"], 
     Item["spinxyz", "spinxyz.nb", CopyTag -> None, IndexTag -> "spinxyz"], 
     Item["spinss", "spinxyz.nb", CopyTag -> None, IndexTag -> "spinss"], 
     Item["spinall", "spinxyz.nb", CopyTag -> None, IndexTag -> "spinall"], 
     Item["spinplus", "spinxyz.nb", CopyTag -> None, IndexTag -> "spinplus"], 
     Item["spinminus", "spinxyz.nb", CopyTag -> None, 
      IndexTag -> "spinminus"]}, {Item["sumCollect", "sumCollect.nb", 
      CopyTag -> None, IndexTag -> "sumCollect"]}, 
    {Item["sumExpand", "sumExpand.nb", CopyTag -> None, 
      IndexTag -> "sumExpand"]}, {Item["sumFullSimplify", 
      "sumFullSimplify.nb", CopyTag -> None, IndexTag -> "sumFullSimplify"]}, 
    {Item["sum", "sum.nb", CopyTag -> None, IndexTag -> "sum"]}, 
    {Item["sumSimplifyKD", "sumSimplifyKD.nb", CopyTag -> None, 
      IndexTag -> "sumSimplifyKD"]}, {Item["sumThread", "sumThread.nb", 
      CopyTag -> None, IndexTag -> "sumThread"]}, 
    {Item["superkomutator", "superkomutator.nb", CopyTag -> None, 
      IndexTag -> "superkomutator"], Item["superantikomutator", 
      "superkomutator.nb", CopyTag -> None, IndexTag -> 
       "superantikomutator"]}, {Item["transformbasis", "transformbasis.nb", 
      CopyTag -> None, IndexTag -> "transformbasis"], 
     Item["transformfunc", "transformbasis.nb", CopyTag -> None, 
      IndexTag -> "transformfunc"]}, 
    {Item["transformQStoIS", "transformQStoIS.nb", CopyTag -> None, 
      IndexTag -> "transformQStoIS"]}, 
    {Item["transformtoLR", "transformtoLR.nb", CopyTag -> None, 
      IndexTag -> "transformtoLR"], Item["lrmap", "transformtoLR.nb", 
      CopyTag -> None, IndexTag -> "lrmap"]}, 
    {Item["transformtoPH", "transformtoPH.nb", CopyTag -> None, 
      IndexTag -> "transformtoPH"]}, {Item["twohop", "twohop.nb", 
      CopyTag -> None, IndexTag -> "twohop"]}, 
    {Item["vacuum", "vacuumlc.nb", CopyTag -> None, IndexTag -> "vacuumlc"]},
    {Item["VACUUM", "VACUUM.nb", CopyTag -> None, IndexTag -> "VACUUM"]}, 
    {Item["vc2ops", "vc2ops.nb", CopyTag -> None, IndexTag -> "vc2ops"]}, 
    {Item["vc", "vc.nb", CopyTag -> None, IndexTag -> "vc"]}, 
    {Item["vev", "vev.nb", CopyTag -> None, IndexTag -> "vev"], 
     Item["vevwick", "vev.nb", CopyTag -> None, IndexTag -> "vevwick"]}, 
    {Item["VMV", "VMV.nb", CopyTag -> None, IndexTag -> "VMV"]}, 
    {Item["wick", "wick.nb", CopyTag -> None, IndexTag -> "wick"]}, 
    {Item["zeroonvac", "zeroonvac.nb", CopyTag -> None, 
      IndexTag -> "zeroonvac"]}}]}]
